[package]
name = "kakeibo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
chrono = "0.4"
dotenvy = "0.15.1"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0"

[dev-dependencies]
mockito = "1.2.0"
